import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { montserrat, fraunces } from "./fonts";
import clsx from "clsx";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={clsx(montserrat.variable, fraunces.variable)}>
      <body className={clsx("min-h-screen bg-background antialiased")}>
        <main className="parent-container">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
